# Generated by Django 6.0.2 on 2026-03-28 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblCategory',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tblchat',
            fields=[
                ('chatID', models.AutoField(primary_key=True, serialize=False)),
                ('senderID', models.IntegerField()),
                ('receiverID', models.IntegerField()),
                ('message', models.TextField(max_length=500)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='chat_attachments/')),
                ('createdDT', models.DateTimeField(auto_now_add=True)),
                ('isRead', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='tblClient',
            fields=[
                ('clientID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('address', models.TextField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.TextField(max_length=10)),
                ('bloodGroup', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='tblDoctor',
            fields=[
                ('doctorID', models.AutoField(primary_key=True, serialize=False)),
                ('displayName', models.TextField(max_length=50)),
                ('displayContact', models.TextField(max_length=15)),
                ('bio', models.TextField(max_length=500)),
                ('displayAddress', models.TextField(max_length=100)),
                ('yearOfExperience', models.IntegerField()),
                ('licenseNo', models.TextField(max_length=50)),
                ('documents', models.FileField(upload_to='doctor_documents/')),
                ('mode', models.IntegerField(default=1)),
                ('consultationFees', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tblState',
            fields=[
                ('stateID', models.AutoField(primary_key=True, serialize=False)),
                ('stateName', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tblAppointment',
            fields=[
                ('appointmentID', models.AutoField(primary_key=True, serialize=False)),
                ('appointmentDate', models.DateField()),
                ('appointmentTime', models.TimeField()),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('meetLink', models.TextField(blank=True, max_length=500, null=True)),
                ('isAccepted', models.BooleanField(default=False)),
                ('isRejected', models.BooleanField(default=False)),
                ('createdDT', models.DateTimeField(auto_now_add=True, null=True)),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tblclient')),
                ('doctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbldoctor')),
            ],
        ),
        migrations.CreateModel(
            name='tblDoctorAttachment',
            fields=[
                ('attachmentID', models.AutoField(primary_key=True, serialize=False)),
                ('attachment', models.FileField(upload_to='attachments/')),
                ('doctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbldoctor')),
            ],
        ),
        migrations.CreateModel(
            name='tblDoctorCaseStudy',
            fields=[
                ('caseStudyID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=150)),
                ('symptoms', models.TextField(max_length=1000)),
                ('diagnosis', models.TextField(max_length=1000)),
                ('treatment', models.TextField(max_length=1000)),
                ('notes', models.TextField(blank=True, max_length=1500)),
                ('createdDT', models.DateTimeField(auto_now_add=True)),
                ('updatedDT', models.DateTimeField(auto_now=True)),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tblclient')),
                ('doctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbldoctor')),
            ],
        ),
        migrations.CreateModel(
            name='tblDoctorImages',
            fields=[
                ('doctorImageID', models.AutoField(primary_key=True, serialize=False)),
                ('imageURL', models.ImageField(upload_to='doctor_images/')),
                ('doctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbldoctor')),
            ],
        ),
        migrations.CreateModel(
            name='tblDoctorPost',
            fields=[
                ('doctorPostID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('thumbnail', models.ImageField(upload_to='images/')),
                ('createDT', models.DateTimeField(auto_now_add=True)),
                ('doctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbldoctor')),
            ],
        ),
        migrations.CreateModel(
            name='tblPayment',
            fields=[
                ('paymentID', models.AutoField(primary_key=True, serialize=False)),
                ('doctorFees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platformFee', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('totalAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('paymentMethod', models.CharField(choices=[('razorpay', 'Razorpay (Online)'), ('cash', 'Cash at Clinic')], default='razorpay', max_length=20)),
                ('paymentStatus', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cash', 'Cash at Clinic')], default='pending', max_length=20)),
                ('createdDT', models.DateTimeField(auto_now_add=True)),
                ('appointmentID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='user.tblappointment')),
            ],
        ),
        migrations.CreateModel(
            name='tblCity',
            fields=[
                ('cityID', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.TextField(max_length=50)),
                ('stateID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tblstate')),
            ],
        ),
        migrations.CreateModel(
            name='tblSubcategory',
            fields=[
                ('subcategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('subcategoryName', models.TextField(max_length=50)),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tblcategory')),
            ],
        ),
        migrations.AddField(
            model_name='tbldoctor',
            name='subcategoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tblsubcategory'),
        ),
        migrations.CreateModel(
            name='tblDiagnosis',
            fields=[
                ('diagnosisID', models.AutoField(primary_key=True, serialize=False)),
                ('diagnosisName', models.CharField(max_length=150)),
                ('subcategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='user.tblsubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='tblclientHistory',
            fields=[
                ('clientHistoryID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, max_length=100, null=True)),
                ('symptoms', models.TextField(blank=True, max_length=500, null=True)),
                ('customDiagnosis', models.TextField(blank=True, max_length=500, null=True)),
                ('prescription', models.TextField(max_length=500)),
                ('additionalNotes', models.TextField(blank=True, max_length=500, null=True)),
                ('createdDT', models.DateTimeField(auto_now_add=True)),
                ('isMarkedSpecial', models.BooleanField(default=False)),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tblclient')),
                ('diagnosisID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.tbldiagnosis')),
                ('doctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbldoctor')),
                ('subcategoryID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.tblsubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='tblUser',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=10)),
                ('registrationDT', models.DateTimeField(auto_now_add=True)),
                ('profilePic', models.ImageField(upload_to='images/')),
                ('email', models.TextField(max_length=100)),
                ('mobileNumber', models.TextField(max_length=15)),
                ('IsDoctor', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('cityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tblcity')),
            ],
        ),
        migrations.CreateModel(
            name='tblReview',
            fields=[
                ('reviewID', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('review', models.TextField(max_length=500)),
                ('createdDT', models.DateTimeField(auto_now_add=True)),
                ('doctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbldoctor')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbluser')),
            ],
        ),
        migrations.CreateModel(
            name='tblnotification',
            fields=[
                ('notificationID', models.AutoField(primary_key=True, serialize=False)),
                ('senderID', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(max_length=500)),
                ('createdDT', models.DateTimeField(auto_now_add=True)),
                ('isRead', models.BooleanField(default=False)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbluser')),
            ],
        ),
        migrations.AddField(
            model_name='tbldoctor',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbluser'),
        ),
        migrations.CreateModel(
            name='tblComments',
            fields=[
                ('commentsID', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=500)),
                ('createdDT', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='user.tblcomments')),
                ('doctorPostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbldoctorpost')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbluser')),
            ],
        ),
        migrations.AddField(
            model_name='tblclient',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbluser'),
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbluser')),
            ],
        ),
        migrations.CreateModel(
            name='tblDoctorSchedule',
            fields=[
                ('scheduleID', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('doctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbldoctor')),
            ],
            options={
                'ordering': ['day_of_week'],
                'unique_together': {('doctorID', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='tblFollow',
            fields=[
                ('followID', models.AutoField(primary_key=True, serialize=False)),
                ('followedDT', models.DateTimeField(auto_now_add=True)),
                ('doctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbldoctor')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbluser')),
            ],
            options={
                'unique_together': {('userID', 'doctorID')},
            },
        ),
    ]
