# Generated by Django 6.0.2 on 2026-04-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldoctor',
            name='consultationFees',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
