# Generated by Django 6.0.2 on 2026-04-03 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_tbldoctor_consultationfees'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblSupportTicket',
            fields=[
                ('ticketID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
                ('subject', models.TextField(max_length=150)),
                ('message', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('createdDT', models.DateTimeField(auto_now_add=True)),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.tbluser')),
            ],
        ),
    ]
