# Generated by Django 6.0.2 on 2026-03-26 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_tblclienthistory_subcategoryid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblclienthistory',
            old_name='diagnosis',
            new_name='customDiagnosis',
        ),
        migrations.CreateModel(
            name='tblDiagnosis',
            fields=[
                ('diagnosisID', models.AutoField(primary_key=True, serialize=False)),
                ('diagnosisName', models.CharField(max_length=150)),
                ('subcategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='user.tblsubcategory')),
            ],
        ),
        migrations.AddField(
            model_name='tblclienthistory',
            name='diagnosisID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.tbldiagnosis'),
        ),
    ]
