# Generated by Django 6.0.2 on 2026-03-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_diagnosis_tblclienthistory_customdiagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblchat',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
    ]
