# Generated by Django 6.0.2 on 2026-04-14 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_tblsupportticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblPatientReport',
            fields=[
                ('reportID', models.AutoField(primary_key=True, serialize=False)),
                ('reportTitle', models.CharField(max_length=200)),
                ('reportDescription', models.TextField(blank=True, max_length=500, null=True)),
                ('reportFile', models.FileField(upload_to='patient_reports/')),
                ('uploadedDT', models.DateTimeField(auto_now_add=True)),
                ('clientHistoryID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_reports', to='user.tblclienthistory')),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tblclient')),
            ],
        ),
    ]
