# Generated by Django 6.0.2 on 2026-03-28 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_tblchat_attachment'),
        ('user', '0004_tblchat_attachment_alter_tblchat_message'),
    ]

    operations = [
    ]
