# Generated by Django 6.0.2 on 2026-04-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_tblpatientreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblappointment',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
