# Generated by Django 6.0.2 on 2026-03-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_tblappointment_isrejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldoctor',
            name='documents',
            field=models.FileField(default=1, upload_to='doctor_documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbldoctor',
            name='licenseNo',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbldoctor',
            name='yearOfExperience',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
