# Generated by Django 6.0.2 on 2026-03-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_tbldoctor_documents_tbldoctor_licenseno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblclient',
            name='address',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
