# Generated by Django 6.0.2 on 2026-03-15 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_tblclient_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblDoctorAttachment',
            fields=[
                ('attachmentID', models.AutoField(primary_key=True, serialize=False)),
                ('attachment', models.FileField(upload_to='attachments/')),
                ('doctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbldoctor')),
            ],
        ),
    ]
