# Generated by Django 6.0.2 on 2026-03-17 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_tbldoctorattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblDoctorSchedule',
            fields=[
                ('scheduleID', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('doctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbldoctor')),
            ],
            options={
                'ordering': ['day_of_week'],
                'unique_together': {('doctorID', 'day_of_week')},
            },
        ),
    ]
