# Generated by Django 6.0.2 on 2026-03-18 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_tbldoctorschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblDoctorCaseStudy',
            fields=[
                ('caseStudyID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=150)),
                ('symptoms', models.TextField(max_length=1000)),
                ('diagnosis', models.TextField(max_length=1000)),
                ('treatment', models.TextField(max_length=1000)),
                ('notes', models.TextField(blank=True, max_length=1500)),
                ('createdDT', models.DateTimeField(auto_now_add=True)),
                ('updatedDT', models.DateTimeField(auto_now=True)),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tblclient')),
                ('doctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbldoctor')),
            ],
        ),
    ]
