# Generated by Django 6.0.2 on 2026-03-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_tbldoctorcasestudy'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblclienthistory',
            name='additionalNotes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tblclienthistory',
            name='diagnosis',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tblclienthistory',
            name='symptoms',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tblclienthistory',
            name='title',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
