# Generated by Django 6.0.2 on 2026-03-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_tblclienthistory_additionalnotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblappointment',
            name='createdDT',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
