# Generated by Django 6.0.2 on 2026-03-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblnotification',
            name='senderID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
