# Generated by Django 6.0.2 on 2026-03-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_tblnotification_senderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluser',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
