# Generated by Django 6.0.2 on 2026-03-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_tbluser_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblappointment',
            name='consultationMode',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tblappointment',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tblappointment',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tbldoctor',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
