# Generated by Django 6.0.2 on 2026-03-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_tblappointment_consultationmode_tblappointment_fees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblappointment',
            name='consultationMode',
        ),
        migrations.RemoveField(
            model_name='tblappointment',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='tblappointment',
            name='isPaid',
        ),
        migrations.RemoveField(
            model_name='tbldoctor',
            name='fees',
        ),
        migrations.AddField(
            model_name='tblappointment',
            name='meetLink',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tblappointment',
            name='mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=20),
        ),
    ]
