# Generated by Django 6.0.2 on 2026-03-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_remove_tblappointment_consultationmode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldoctor',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
