# Generated by Django 6.0.2 on 2026-03-24 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_tbldoctor_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldoctor',
            name='consultationFees',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='tblPayment',
            fields=[
                ('paymentID', models.AutoField(primary_key=True, serialize=False)),
                ('doctorFees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platformFee', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('totalAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('paymentMethod', models.CharField(choices=[('razorpay', 'Razorpay (Online)'), ('cash', 'Cash at Clinic')], default='razorpay', max_length=20)),
                ('paymentStatus', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cash', 'Cash at Clinic')], default='pending', max_length=20)),
                ('createdDT', models.DateTimeField(auto_now_add=True)),
                ('appointmentID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='user.tblappointment')),
            ],
        ),
    ]
