"""
Django settings for carespot project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
    
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j8vgi^1ojsar-uus%=g-v=egl^+m!=i%bf8w#a1^h_kusv5f+8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user',
    'customadmin',
]

UNFOLD = {
    "SITE_TITLE": "CareSpot Admin",
    "SITE_HEADER": "CareSpot Management",
    "SITE_SYMBOL": "medical_services", # Material icon
    "SITE_LOGO": "/media/images/careSpotText.png",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "THEME": "light",
    "STYLES": [
        "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css",
        lambda request: "/static/admin/css/admin_premium.css",
    ],
    "COLORS": {
        "primary": {
            "50": "204, 251, 241",  # Light Teal (#CCFBF1)
            "100": "153, 246, 228",
            "200": "94, 234, 212",
            "300": "45, 212, 191",
            "400": "20, 184, 166",
            "500": "13, 148, 136",  # Primary Teal (#0D9488)
            "600": "15, 118, 110",
            "700": "15, 98, 92",
            "800": "17, 78, 74",
            "900": "19, 63, 60",
            "950": "8, 47, 45",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Core Management",
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": "/admin/",
                    },
                    {
                        "title": "Users",
                        "icon": "people",
                        "link": "/admin/user/tbluser/",
                    },
                ],
            },
            {
                "title": "Medical Operations",
                "items": [
                    {
                        "title": "Doctors",
                        "icon": "medical_services",
                        "link": "/admin/user/tbldoctor/",
                    },
                    {
                        "title": "Appointments",
                        "icon": "calendar_month",
                        "link": "/admin/user/tblappointment/",
                    },
                    {
                        "title": "Clients (Patients)",
                        "icon": "person",
                        "link": "/admin/user/tblclient/",
                    },
                ],
            },
            {
                "title": "Support & Feedback",
                "items": [
                    {
                        "title": "Tickets",
                        "icon": "confirmation_number",
                        "link": "/admin/user/tblsupportticket/",
                    },
                    {
                        "title": "Reviews",
                        "icon": "star",
                        "link": "/admin/user/tblreview/",
                    },
                ],
            },
        ],
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'user.middleware.AutoRejectMiddleware',
    'user.middleware.UserActivityMiddleware',
    'user.middleware.NoCacheMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
]

ROOT_URLCONF = 'carespot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'user' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'carespot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

# import os
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL="/media/"
MEDIA_ROOT=BASE_DIR/'media'

# Allow iframes from the same origin to display PDFs inline
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Browser band hone par session expire ho jayega
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'novacafecenter@gmail.com'
EMAIL_HOST_PASSWORD = 'htet eprc cprw cbfe'

# Razorpay Payment Gateway Settings
RAZORPAY_KEY_ID = 'rzp_test_SYWFItRkNGUREZ'  # Replace with your Razorpay Key ID
RAZORPAY_KEY_SECRET = 'Kl7bIXfXnUkDeEeSww8PvRqm'    # Replace with your Razorpay Key Secret
PLATFORM_FEE = 5  # Platform charge in INR